#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/gb18030_and_gbk/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/gb18030_and_gbk
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= gb18030_and_gbk
PGFILEDESC	= "gb18030 <-> gbk text conversions"

include $(srcdir)/../proc.mk
