/*-------------------------------------------------------------------------
 *
 * ora_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef ORA_KWLIST_D_H
#define ORA_KWLIST_D_H

#include "common/kwlookup.h"

static const char OraScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"accessible\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authid\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_float\0"
	"binary_float_infinity\0"
	"binary_float_nan\0"
	"bit\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compile\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"date\0"
	"day\0"
	"deallocate\0"
	"debug\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"editionable\0"
	"else\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"exec\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extend\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"ivysql\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_object\0"
	"json_objectagg\0"
	"json_scalar\0"
	"json_serialize\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"loop\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"metadata\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"nocache\0"
	"nocopy\0"
	"nocycle\0"
	"noextend\0"
	"nokeep\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"noneditionable\0"
	"noorder\0"
	"normalize\0"
	"normalized\0"
	"noscale\0"
	"noshard\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"nvl\0"
	"nvl2\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"package\0"
	"parallel\0"
	"parallel_enable\0"
	"parameter\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"pipelined\0"
	"placing\0"
	"plans\0"
	"policy\0"
	"polymorphic\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"range\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"relies_on\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"result_cache\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"scale\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"settings\0"
	"shard\0"
	"share\0"
	"sharing\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"sql\0"
	"sql_macro\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"systimestamp\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"user\0"
	"userenv\0"
	"using\0"
	"using_nls_comp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"volatile\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 OraScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	40,
	47,
	51,
	57,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	125,
	128,
	132,
	143,
	153,
	164,
	175,
	178,
	185,
	192,
	202,
	209,
	223,
	232,
	239,
	245,
	253,
	260,
	267,
	281,
	304,
	322,
	335,
	357,
	374,
	378,
	386,
	391,
	399,
	402,
	407,
	413,
	418,
	425,
	433,
	442,
	447,
	452,
	460,
	466,
	471,
	481,
	497,
	503,
	514,
	520,
	526,
	534,
	543,
	551,
	561,
	568,
	576,
	584,
	593,
	600,
	610,
	618,
	630,
	643,
	657,
	666,
	677,
	688,
	700,
	708,
	717,
	728,
	733,
	738,
	745,
	751,
	755,
	760,
	768,
	784,
	797,
	810,
	825,
	838,
	856,
	869,
	876,
	882,
	887,
	896,
	901,
	905,
	916,
	922,
	926,
	934,
	942,
	949,
	957,
	966,
	977,
	986,
	994,
	1001,
	1011,
	1022,
	1030,
	1036,
	1041,
	1048,
	1062,
	1073,
	1081,
	1089,
	1098,
	1101,
	1110,
	1117,
	1124,
	1129,
	1134,
	1146,
	1151,
	1158,
	1167,
	1177,
	1181,
	1186,
	1193,
	1199,
	1206,
	1214,
	1224,
	1234,
	1239,
	1247,
	1254,
	1262,
	1273,
	1280,
	1290,
	1299,
	1307,
	1313,
	1320,
	1326,
	1333,
	1342,
	1348,
	1354,
	1364,
	1368,
	1374,
	1382,
	1389,
	1397,
	1404,
	1409,
	1414,
	1423,
	1433,
	1443,
	1450,
	1456,
	1464,
	1473,
	1479,
	1488,
	1495,
	1503,
	1508,
	1515,
	1522,
	1527,
	1532,
	1541,
	1544,
	1550,
	1560,
	1570,
	1579,
	1586,
	1589,
	1597,
	1607,
	1617,
	1624,
	1630,
	1638,
	1647,
	1655,
	1664,
	1674,
	1681,
	1687,
	1693,
	1699,
	1711,
	1718,
	1726,
	1730,
	1738,
	1748,
	1757,
	1762,
	1770,
	1773,
	1780,
	1790,
	1797,
	1802,
	1807,
	1818,
	1832,
	1844,
	1859,
	1871,
	1886,
	1891,
	1895,
	1900,
	1906,
	1915,
	1921,
	1926,
	1934,
	1942,
	1952,
	1958,
	1963,
	1969,
	1974,
	1980,
	1987,
	1992,
	1998,
	2008,
	2023,
	2032,
	2037,
	2044,
	2051,
	2056,
	2061,
	2069,
	2075,
	2083,
	2096,
	2105,
	2111,
	2120,
	2127,
	2134,
	2143,
	2148,
	2155,
	2161,
	2166,
	2171,
	2177,
	2181,
	2190,
	2198,
	2204,
	2208,
	2213,
	2217,
	2221,
	2226,
	2231,
	2234,
	2242,
	2249,
	2257,
	2266,
	2273,
	2284,
	2295,
	2300,
	2315,
	2323,
	2333,
	2344,
	2352,
	2360,
	2364,
	2372,
	2379,
	2387,
	2394,
	2399,
	2406,
	2412,
	2419,
	2427,
	2431,
	2436,
	2443,
	2446,
	2450,
	2457,
	2462,
	2466,
	2469,
	2474,
	2483,
	2490,
	2498,
	2501,
	2507,
	2518,
	2525,
	2529,
	2535,
	2540,
	2549,
	2557,
	2568,
	2574,
	2580,
	2588,
	2597,
	2613,
	2623,
	2630,
	2638,
	2648,
	2656,
	2665,
	2675,
	2683,
	2689,
	2696,
	2708,
	2717,
	2727,
	2737,
	2745,
	2754,
	2763,
	2771,
	2777,
	2788,
	2799,
	2809,
	2820,
	2828,
	2840,
	2846,
	2852,
	2856,
	2861,
	2866,
	2875,
	2883,
	2893,
	2897,
	2908,
	2920,
	2928,
	2936,
	2945,
	2953,
	2963,
	2970,
	2981,
	2989,
	2997,
	3003,
	3011,
	3020,
	3033,
	3040,
	3050,
	3058,
	3064,
	3071,
	3077,
	3082,
	3091,
	3098,
	3106,
	3115,
	3119,
	3124,
	3132,
	3137,
	3147,
	3154,
	3160,
	3167,
	3175,
	3182,
	3189,
	3196,
	3205,
	3212,
	3221,
	3231,
	3244,
	3251,
	3259,
	3272,
	3276,
	3282,
	3287,
	3296,
	3302,
	3308,
	3316,
	3321,
	3329,
	3336,
	3341,
	3350,
	3359,
	3364,
	3368,
	3378,
	3385,
	3396,
	3402,
	3412,
	3423,
	3429,
	3436,
	3444,
	3451,
	3458,
	3464,
	3477,
	3487,
	3495,
	3505,
	3513,
	3519,
	3526,
	3538,
	3551,
	3557,
	3564,
	3576,
	3587,
	3592,
	3601,
	3611,
	3616,
	3621,
	3626,
	3631,
	3641,
	3644,
	3653,
	3665,
	3675,
	3681,
	3689,
	3694,
	3699,
	3708,
	3716,
	3721,
	3727,
	3735,
	3745,
	3757,
	3769,
	3775,
	3782,
	3790,
	3799,
	3808,
	3814,
	3821,
	3826,
	3834,
	3840,
	3855,
	3862,
	3868,
	3877,
	3887,
	3893,
	3900,
	3908,
	3917,
	3926,
	3934,
	3942,
	3950,
	3955,
	3961,
	3970,
	3975,
	3981,
	3992,
	3999,
	4004,
	4011,
	4019,
	4024,
	4032,
	4038,
	4042,
	4056,
	4066,
	4077,
	4087,
	4097,
	4111,
	4120,
	4126,
	4134,
	4147,
	4156,
	4161,
	4165,
};

#define ORASCANKEYWORDS_NUM_KEYWORDS 532

static int
OraScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1065] = {
		146,   389,   -314,  32767, 32767, 237,   32767, 0,
		355,   498,   259,   32767, 32767, 0,     154,   362,
		127,   32767, 32767, 32767, 32767, 144,   32767, 32767,
		298,   0,     0,     423,   6,     49,    482,   315,
		32767, 32767, 142,   505,   -259,  32767, 355,   306,
		56,    145,   386,   -381,  -48,   32767, 24,    -535,
		0,     -134,  32767, 32767, 310,   612,   256,   286,
		715,   32767, 32767, 357,   32767, 8,     248,   172,
		32767, 87,    -137,  409,   0,     32767, 32767, 32767,
		660,   32767, 82,    -131,  32767, 32767, -23,   -166,
		0,     399,   32767, 217,   0,     433,   -64,   198,
		32767, 0,     32767, 203,   209,   32767, 58,    32767,
		0,     -164,  422,   0,     32767, 32767, 342,   465,
		177,   504,   -68,   290,   -613,  32767, 0,     32767,
		32767, 0,     -318,  369,   125,   153,   234,   -196,
		-14,   251,   143,   32767, 112,   482,   32767, 32767,
		32767, 32767, 0,     32767, 0,     32767, 32767, 32767,
		-110,  91,    32767, 205,   32767, 32767, -126,  62,
		-198,  316,   139,   475,   32767, 191,   -52,   32767,
		32767, 437,   169,   775,   63,    871,   253,   189,
		32767, 32767, 32767, 32767, 32767, 32767, 32767, 121,
		25,    188,   32767, 32767, 32767, -135,  27,    0,
		117,   0,     336,   32767, 0,     32767, 196,   388,
		32767, 32767, 419,   32767, -37,   32767, 32767, 41,
		32767, 32767, 32767, 32767, 32767, 0,     32767, 0,
		0,     46,    32767, 32767, 307,   259,   398,   385,
		-607,  247,   118,   32767, 1140,  32767, 32767, 371,
		582,   215,   32767, 295,   32767, 32767, 0,     1168,
		114,   560,   32767, 0,     292,   32767, -225,  -247,
		-114,  491,   527,   32767, 0,     32767, -267,  32767,
		32767, 32767, -38,   32767, 200,   404,   32767, 32767,
		32767, 145,   32767, -186,  -590,  379,   32767, 242,
		-652,  32767, 32767, 32767, 32767, 429,   -715,  32767,
		266,   14,    108,   32767, 0,     237,   32767, 29,
		198,   32767, 738,   0,     46,    150,   32767, -21,
		32767, 0,     32767, 32767, 290,   170,   32767, 541,
		0,     92,    257,   0,     32767, 778,   263,   32767,
		32767, 32767, 0,     32767, 32767, 0,     1,     976,
		326,   -171,  32767, 32767, 0,     503,   180,   32767,
		0,     32767, -35,   32767, 239,   414,   32767, 32767,
		32767, 32767, 1197,  0,     0,     157,   32767, -235,
		96,    32767, -382,  487,   88,    271,   32767, 32767,
		104,   32767, 32767, 32767, 0,     32767, 32767, 271,
		522,   0,     260,   32767, 32767, 635,   0,     506,
		70,    834,   155,   258,   554,   8,     485,   81,
		449,   456,   479,   32767, -63,   324,   0,     -177,
		-147,  464,   32767, 203,   32767, 0,     450,   32767,
		290,   203,   597,   -86,   -357,  32767, 408,   0,
		-55,   25,    32767, 32767, -159,  108,   0,     21,
		32767, -363,  116,   -36,   303,   32767, 0,     415,
		0,     729,   32767, -89,   0,     402,   -203,  14,
		64,    -289,  504,   0,     -73,   0,     -721,  32767,
		32767, 31,    32767, 32767, 32767, 233,   519,   32767,
		506,   186,   300,   -58,   0,     32767, 26,    -55,
		1099,  -19,   -159,  32767, 0,     32767, 32767, 32767,
		32767, 412,   155,   32767, -280,  84,    -12,   32767,
		0,     136,   133,   32767, -250,  -363,  473,   32767,
		32767, 224,   193,   32767, 684,   0,     190,   247,
		32767, 0,     32767, -514,  40,    140,   -640,  0,
		32767, 45,    32767, 0,     415,   113,   737,   -325,
		272,   444,   32767, 32767, 32767, 32767, 638,   0,
		32767, 802,   22,    -75,   143,   32767, 32767, -120,
		32767, 32767, 789,   32767, 455,   32767, -9,    32767,
		593,   32767, 624,   -113,  32767, 32767, 94,    32767,
		376,   -247,  53,    413,   0,     0,     0,     262,
		238,   127,   32767, 263,   241,   32767, 350,   0,
		0,     32767, 32767, 32767, 0,     335,   -71,   -466,
		840,   32767, 32767, 32767, 265,   -142,  32767, 32767,
		384,   223,   32767, 32767, 32767, -66,   25,    290,
		32767, 32767, 32767, 32767, 32767, 0,     32767, 11,
		32767, 214,   32767, 32767, 265,   32767, 32767, 32767,
		373,   32767, 0,     32767, 372,   264,   309,   -197,
		32767, 233,   192,   4,     32767, 73,    -478,  32767,
		32767, 477,   0,     32767, 32767, 337,   32767, 936,
		802,   72,    32767, 93,    164,   -238,  310,   330,
		428,   71,    422,   487,   32767, 32767, 185,   32767,
		42,    32767, 32767, 158,   273,   -278,  -319,  0,
		32767, 339,   32767, 0,     32767, 0,     0,     32767,
		32767, 68,    345,   113,   171,   37,    0,     32767,
		32767, 0,     469,   -98,   0,     915,   435,   -384,
		32767, 32767, 32767, 32767, 32767, 150,   215,   0,
		241,   32767, 32767, 0,     32767, 354,   -677,  32767,
		-111,  0,     32767, 32767, 153,   17,    291,   336,
		-174,  836,   32767, 358,   32767, -101,  220,   0,
		178,   0,     32767, 32767, 100,   0,     0,     32767,
		1,     246,   32767, 321,   74,    486,   197,   418,
		-52,   296,   32767, 284,   164,   811,   32767, -298,
		38,    32767, 315,   110,   32767, 696,   0,     32767,
		255,   112,   181,   32767, -130,  32767, 32767, 32767,
		32767, 415,   254,   0,     0,     0,     123,   85,
		0,     346,   85,    32767, 32767, -111,  -702,  32767,
		32767, -461,  -85,   32767, 32767, 353,   -178,  695,
		157,   331,   1100,  338,   0,     -194,  -115,  32767,
		0,     0,     32767, 234,   510,   147,   32767, 32767,
		-45,   32767, 32767, 32767, 0,     32767, 12,    165,
		32767, 32767, 32767, 32767, 152,   -232,  32767, 32767,
		332,   40,    32767, 32767, 32767, -516,  464,   500,
		32767, 32767, 264,   32767, 0,     0,     77,    -200,
		0,     76,    -37,   -53,   32767, 42,    0,     -31,
		91,    32767, 32767, 32767, 121,   0,     0,     32767,
		425,   32767, 87,    32767, -756,  -190,  344,   32767,
		32767, 32767, 32767, 32767, 47,    326,   -102,  0,
		32767, 0,     845,   32767, -314,  32767, 29,    32767,
		0,     32767, 395,   32767, 32767, 32767, 0,     58,
		471,   44,    32767, 32767, -361,  32767, 321,   0,
		32767, 32767, 0,     371,   -55,   0,     -500,  515,
		32767, 327,   0,     256,   0,     650,   13,    32767,
		32767, 32767, 250,   216,   235,   913,   411,   32767,
		445,   32767, 22,    32767, 32767, 0,     -33,   32767,
		32767, 387,   0,     32767, 32767, 32767, 320,   -37,
		-81,   0,     -371,  516,   66,    32767, 32767, -253,
		32767, 32767, 32767, 32767, 32767, 32767, -31,   32767,
		187,   32767, -315,  510,   32767, 32767, 101,   440,
		32767, 32767, 363,   32767, 0,     176,   0,     136,
		32767, 299,   236,   32767, 221,   32767, 32767, 19,
		354,   32767, 32767, 0,     209,   -18,   416,   32767,
		450,   232,   32767, 24,    32767, 32767, 15,    32767,
		676,   27,    0,     157,   32767, 124,   375,   0,
		-384,  32767, 32767, -162,  18,    32767, 0,     322,
		10,    225,   0,     58,    32767, 0,     32767, 0,
		32767, -73,   0,     32767, 32767, 32767, 32767, -835,
		32767, 32767, 457,   -327,  798,   395,   32767, 0,
		-785,  222,   0,     32767, 32767, 32767, 32767, 29,
		32767, 32767, 0,     32767, 0,     32767, 0,     32767,
		650,   442,   0,     0,     32767, 336,   0,     183,
		32767, 32767, 0,     0,     419,   704,   32767, 306,
		32767, 0,     157,   0,     32767, 3,     32767, 104,
		32767, 32767, 6,     78,    144,   32767, 74,    32767,
		32767, 190,   32767, 32767, 0,     534,   -157,  32767,
		-203,  0,     32767, 0,     0,     -611,  0,     0,
		37,    0,     32767, 32767, 0,     441,   496,   32767,
		0,     0,     337,   531,   32767, 32767, 32767, 365,
		314,   32767, 79,    0,     -409,  32767, 5,     116,
		0
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1065] + h[b % 1065];
}

const ScanKeywordList OraScanKeywords = {
	OraScanKeywords_kw_string,
	OraScanKeywords_kw_offsets,
	OraScanKeywords_hash_func,
	ORASCANKEYWORDS_NUM_KEYWORDS,
	22
};

#endif							/* ORA_KWLIST_D_H */
