# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Minimal configuration for getting started
language: "en-US"
reviews:
  profile: "chill"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["master", "IVORY_REL_5_STABLE"]
  path_filters:
    - "**/*.out"  # Include test output files
  path_instructions:
    - path: "**/expected/*.out"
      instructions: |
        These are expected test outputs from pg_regress. Review for:
        - Correctness of query results
        - Proper Oracle compatibility behavior
        - Edge case coverage
        - Consistency with corresponding .sql test files
    - path: "**/sql/*.sql"
      instructions: |
        Test SQL files. Ensure comprehensive coverage of features.
