/*-------------------------------------------------------------------------
 *
 * ora_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef ORA_KWLIST_D_H
#define ORA_KWLIST_D_H

#include "common/kwlookup.h"

static const char OraScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"accessible\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authid\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_float\0"
	"binary_float_infinity\0"
	"binary_float_nan\0"
	"bit\0"
	"body\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compile\0"
	"compression\0"
	"concurrently\0"
	"conditional\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"date\0"
	"day\0"
	"deallocate\0"
	"debug\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"editionable\0"
	"else\0"
	"empty\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enforced\0"
	"enum\0"
	"error\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"exec\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extend\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"ivysql\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_exists\0"
	"json_object\0"
	"json_objectagg\0"
	"json_query\0"
	"json_scalar\0"
	"json_serialize\0"
	"json_table\0"
	"json_value\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listagg\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"loop\0"
	"lsn\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"merge_action\0"
	"metadata\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"nested\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"nocache\0"
	"nocopy\0"
	"nocycle\0"
	"noextend\0"
	"nokeep\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"noneditionable\0"
	"noorder\0"
	"noparallel\0"
	"normalize\0"
	"normalized\0"
	"noscale\0"
	"noshard\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"nvl\0"
	"nvl2\0"
	"object\0"
	"objects\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"omit\0"
	"on\0"
	"online\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parallel\0"
	"parallel_enable\0"
	"parameter\0"
	"paramslength\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"path\0"
	"pgextract\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"polymorphic\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"quotes\0"
	"range\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"relies_on\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"respect\0"
	"restart\0"
	"restrict\0"
	"result_cache\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rowid\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"scale\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"settings\0"
	"shard\0"
	"share\0"
	"sharing\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"specification\0"
	"sql\0"
	"sql_macro\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"string\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"systimestamp\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unconditional\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"updatexml\0"
	"user\0"
	"userenv\0"
	"using\0"
	"using_nls_comp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"wait\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 OraScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	40,
	47,
	51,
	57,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	125,
	128,
	132,
	143,
	153,
	164,
	175,
	178,
	185,
	192,
	202,
	209,
	223,
	232,
	239,
	245,
	253,
	260,
	267,
	281,
	304,
	322,
	335,
	357,
	374,
	378,
	383,
	391,
	396,
	404,
	407,
	412,
	418,
	423,
	430,
	438,
	447,
	452,
	457,
	465,
	471,
	476,
	486,
	502,
	508,
	519,
	525,
	531,
	539,
	548,
	556,
	566,
	573,
	581,
	589,
	598,
	605,
	615,
	623,
	635,
	648,
	660,
	674,
	683,
	694,
	705,
	717,
	725,
	734,
	745,
	750,
	755,
	762,
	768,
	772,
	777,
	785,
	801,
	814,
	827,
	842,
	855,
	873,
	886,
	893,
	899,
	904,
	913,
	918,
	922,
	933,
	939,
	943,
	951,
	959,
	966,
	974,
	983,
	994,
	1003,
	1011,
	1018,
	1028,
	1039,
	1047,
	1053,
	1058,
	1065,
	1079,
	1090,
	1098,
	1106,
	1115,
	1118,
	1127,
	1134,
	1141,
	1146,
	1151,
	1163,
	1168,
	1174,
	1181,
	1190,
	1200,
	1204,
	1213,
	1218,
	1224,
	1231,
	1237,
	1244,
	1252,
	1262,
	1272,
	1277,
	1285,
	1292,
	1300,
	1311,
	1318,
	1328,
	1337,
	1345,
	1351,
	1358,
	1364,
	1371,
	1380,
	1386,
	1392,
	1402,
	1406,
	1412,
	1420,
	1427,
	1435,
	1442,
	1447,
	1452,
	1461,
	1471,
	1481,
	1488,
	1494,
	1502,
	1511,
	1517,
	1526,
	1533,
	1541,
	1546,
	1553,
	1560,
	1565,
	1570,
	1579,
	1582,
	1589,
	1595,
	1605,
	1615,
	1624,
	1631,
	1634,
	1642,
	1652,
	1662,
	1669,
	1675,
	1683,
	1692,
	1700,
	1709,
	1719,
	1726,
	1732,
	1738,
	1744,
	1756,
	1763,
	1771,
	1775,
	1783,
	1793,
	1802,
	1807,
	1817,
	1825,
	1828,
	1835,
	1845,
	1852,
	1857,
	1862,
	1873,
	1887,
	1899,
	1911,
	1926,
	1937,
	1949,
	1964,
	1975,
	1986,
	1991,
	1995,
	2000,
	2006,
	2015,
	2021,
	2026,
	2034,
	2042,
	2052,
	2058,
	2063,
	2069,
	2074,
	2080,
	2088,
	2095,
	2100,
	2106,
	2116,
	2131,
	2140,
	2145,
	2152,
	2159,
	2164,
	2169,
	2173,
	2181,
	2187,
	2195,
	2208,
	2217,
	2223,
	2236,
	2245,
	2252,
	2259,
	2268,
	2273,
	2280,
	2286,
	2291,
	2296,
	2302,
	2306,
	2315,
	2323,
	2329,
	2336,
	2340,
	2345,
	2349,
	2353,
	2358,
	2363,
	2366,
	2374,
	2381,
	2389,
	2398,
	2405,
	2416,
	2427,
	2432,
	2447,
	2455,
	2466,
	2476,
	2487,
	2495,
	2503,
	2507,
	2515,
	2522,
	2530,
	2537,
	2542,
	2549,
	2555,
	2562,
	2570,
	2574,
	2579,
	2586,
	2594,
	2597,
	2601,
	2608,
	2613,
	2617,
	2622,
	2625,
	2632,
	2637,
	2646,
	2653,
	2661,
	2664,
	2670,
	2681,
	2688,
	2692,
	2698,
	2703,
	2712,
	2720,
	2731,
	2737,
	2743,
	2751,
	2760,
	2769,
	2785,
	2795,
	2808,
	2815,
	2823,
	2833,
	2841,
	2850,
	2855,
	2865,
	2875,
	2883,
	2888,
	2894,
	2901,
	2913,
	2922,
	2932,
	2942,
	2950,
	2959,
	2968,
	2976,
	2982,
	2993,
	3004,
	3014,
	3025,
	3033,
	3045,
	3051,
	3058,
	3064,
	3068,
	3073,
	3078,
	3087,
	3095,
	3103,
	3113,
	3117,
	3128,
	3140,
	3148,
	3156,
	3165,
	3173,
	3183,
	3190,
	3201,
	3209,
	3217,
	3223,
	3231,
	3239,
	3248,
	3261,
	3268,
	3278,
	3286,
	3292,
	3299,
	3305,
	3310,
	3319,
	3326,
	3334,
	3343,
	3347,
	3353,
	3360,
	3365,
	3373,
	3378,
	3388,
	3395,
	3401,
	3408,
	3416,
	3423,
	3430,
	3437,
	3446,
	3453,
	3462,
	3472,
	3485,
	3492,
	3500,
	3513,
	3517,
	3523,
	3528,
	3537,
	3543,
	3549,
	3557,
	3562,
	3570,
	3577,
	3582,
	3591,
	3600,
	3605,
	3612,
	3626,
	3630,
	3640,
	3647,
	3658,
	3664,
	3674,
	3685,
	3691,
	3698,
	3706,
	3713,
	3720,
	3727,
	3733,
	3746,
	3756,
	3764,
	3774,
	3782,
	3788,
	3795,
	3807,
	3820,
	3826,
	3833,
	3845,
	3856,
	3863,
	3868,
	3877,
	3887,
	3892,
	3897,
	3902,
	3907,
	3917,
	3920,
	3929,
	3941,
	3951,
	3957,
	3965,
	3970,
	3975,
	3984,
	3992,
	3997,
	4003,
	4011,
	4021,
	4033,
	4047,
	4059,
	4065,
	4072,
	4080,
	4089,
	4098,
	4104,
	4111,
	4121,
	4126,
	4134,
	4140,
	4155,
	4162,
	4168,
	4177,
	4187,
	4193,
	4200,
	4208,
	4217,
	4226,
	4234,
	4242,
	4250,
	4255,
	4261,
	4269,
	4277,
	4286,
	4291,
	4296,
	4302,
	4313,
	4320,
	4325,
	4332,
	4340,
	4345,
	4353,
	4359,
	4363,
	4377,
	4387,
	4398,
	4408,
	4418,
	4432,
	4441,
	4447,
	4455,
	4468,
	4477,
	4482,
	4486,
};

#define ORASCANKEYWORDS_NUM_KEYWORDS 570

static int
OraScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1141] = {
		32767, 170,   348,   32767, 0,     32767, 0,     32767,
		-59,   32767, 32767, 258,   -90,   551,   230,   514,
		32767, 179,   32767, 32767, 32767, 108,   304,   0,
		290,   -389,  137,   32767, 32767, 164,   890,   189,
		-153,  32767, 57,    192,   379,   -77,   0,     91,
		-45,   230,   32767, 32767, -190,  -596,  67,    0,
		32767, 32767, 899,   32767, 564,   505,   263,   432,
		32767, 32767, 32767, 32767, 259,   80,    32767, 159,
		307,   32767, -683,  -63,   706,   376,   0,     32767,
		367,   114,   373,   32767, 409,   240,   -161,  -257,
		387,   -180,  32,    453,   32767, 97,    149,   32767,
		-506,  92,    -447,  472,   32767, 32767, 0,     32767,
		32767, 32767, -892,  32767, 335,   358,   32767, 0,
		92,    32767, 375,   32767, 49,    293,   -720,  32767,
		335,   32767, 179,   261,   400,   503,   -120,  32767,
		32767, 32767, 436,   0,     0,     24,    176,   36,
		-92,   243,   217,   29,    380,   32767, 298,   0,
		652,   -63,   176,   3,     207,   32767, 291,   32767,
		0,     180,   8,     1400,  391,   -416,  66,    32767,
		-221,  331,   32767, 32767, 32767, 32767, 778,   456,
		366,   148,   339,   32767, 32767, 32767, 0,     380,
		371,   1286,  0,     32767, 232,   329,   0,     19,
		32767, 32767, 45,    32767, 0,     430,   165,   443,
		32767, 32767, 5,     275,   127,   363,   32767, 0,
		32767, 0,     537,   32767, 32767, 22,    -315,  32767,
		551,   32767, 32767, 17,    32767, 48,    0,     0,
		32767, 536,   183,   0,     46,    32767, 546,   26,
		32767, 299,   0,     401,   32767, 189,   32767, 607,
		32767, 32767, 0,     32767, 32767, 0,     -74,   -186,
		291,   32767, 493,   169,   481,   32767, 32767, 374,
		32767, 102,   501,   52,    83,    32767, 672,   251,
		-201,  32767, 85,    0,     694,   1349,  841,   -950,
		129,   945,   0,     0,     0,     -491,  174,   88,
		32767, 32767, 263,   32,    318,   0,     325,   0,
		32767, 32767, 32767, 32767, 32767, 32767, 158,   -40,
		459,   266,   0,     32767, 32767, -242,  32767, -279,
		32767, 32767, 32767, -76,   0,     32767, 181,   32767,
		176,   256,   299,   1172,  32767, 705,   687,   772,
		-228,  32767, 32767, 14,    32767, 32767, 32767, 20,
		32767, 32767, 32767, 548,   32767, 32767, 159,   32767,
		32767, 32767, 265,   32767, 672,   523,   32767, 32767,
		31,    -149,  47,    32767, 128,   392,   32767, 32767,
		32767, -62,   32767, 32767, 32767, 32767, 81,    32767,
		32767, 32767, 300,   -886,  457,   45,    32767, 0,
		32767, 21,    32767, 277,   238,   32767, 32767, 388,
		32767, 422,   294,   69,    32767, 191,   319,   0,
		934,   205,   0,     32767, 32767, 0,     4,     6,
		206,   87,    0,     -521,  32767, -68,   32767, 57,
		425,   0,     32767, 216,   32767, 540,   32767, 0,
		32767, 32767, 32767, 200,   145,   32767, 56,    32767,
		-168,  0,     32767, 0,     286,   32767, 0,     32767,
		32767, 328,   579,   175,   32767, 0,     0,     539,
		0,     304,   -169,  32767, -45,   188,   32767, 0,
		32767, 509,   32767, -722,  32767, 360,   611,   -476,
		198,   0,     19,    421,   32767, 0,     0,     431,
		32767, 0,     0,     32767, 218,   -252,  32767, 32767,
		338,   32767, 462,   0,     32767, 32767, 510,   32767,
		0,     208,   0,     32767, 32767, 32767, 32767, 32767,
		156,   -85,   32767, 32767, 32767, 0,     63,    545,
		0,     32767, 213,   0,     31,    371,   1002,  32767,
		608,   32767, 510,   928,   32767, 32767, 520,   0,
		32767, 32767, 32767, 98,    -299,  534,   0,     0,
		47,    0,     0,     0,     32767, 32767, 32767, 63,
		32767, 0,     261,   32767, 0,     32767, 32767, 77,
		235,   -169,  0,     563,   82,    32767, -161,  32767,
		32767, -597,  259,   -56,   32767, 284,   0,     32767,
		0,     32767, -69,   32767, 483,   32767, 32767, 32767,
		32767, 165,   59,    241,   130,   -248,  0,     0,
		32767, 488,   402,   -244,  32767, 32767, -228,  32767,
		32767, 56,    297,   298,   39,    32767, 32767, 32767,
		0,     32767, 8,     32767, -317,  32767, 32767, 0,
		-66,   0,     -239,  0,     285,   76,    106,   32767,
		116,   485,   68,    32767, 202,   32767, 100,   -23,
		0,     70,    0,     273,   200,   112,   416,   32767,
		-24,   32767, 32767, 32767, 0,     460,   758,   234,
		182,   0,     332,   -51,   -166,  110,   32767, 0,
		652,   32767, 32767, 32767, 278,   0,     32767, 477,
		32767, 32767, 0,     -391,  1401,  -140,  -39,   0,
		67,    -377,  0,     0,     1038,  383,   32767, 199,
		0,     32767, 200,   32767, -82,   -39,   31,    32767,
		279,   32767, 0,     466,   -157,  32767, -67,   253,
		0,     -15,   170,   403,   667,   0,     -12,   32767,
		0,     93,    32767, -491,  171,   352,   0,     907,
		45,    32767, 334,   32767, 0,     72,    32767, 32767,
		32767, 32767, 224,   32767, 32767, 32767, 32767, 32767,
		0,     227,   166,   32767, 254,   32767, -437,  135,
		32767, 600,   32767, -783,  269,   32767, 113,   32767,
		215,   475,   -321,  0,     32767, 143,   32767, 32767,
		-73,   786,   271,   -523,  854,   131,   460,   32767,
		-413,  295,   -399,  32767, 465,   24,    32767, 32767,
		-551,  32767, 32767, 955,   0,     431,   0,     104,
		32767, 32767, 645,   84,    279,   32767, 32767, 82,
		-76,   -30,   32767, 32767, 61,    818,   32767, 0,
		506,   372,   691,   32767, 0,     0,     231,   99,
		0,     32767, 32767, 32767, 32767, 32767, -328,  98,
		326,   106,   406,   0,     32767, -68,   32767, -151,
		35,    32767, -117,  32767, 32767, 32767, 152,   32767,
		32767, 32767, 32767, -408,  32767, 513,   32767, 32767,
		0,     307,   32767, 284,   0,     32767, 32767, 32767,
		32767, -187,  -305,  32767, 32767, 32767, 0,     32767,
		32767, 168,   50,    565,   222,   32767, 32767, 32767,
		32767, 86,    362,   0,     0,     105,   32767, 32767,
		32767, 32767, 32767, 0,     -417,  0,     -155,  -368,
		305,   32767, 490,   350,   32767, 32767, 900,   279,
		524,   275,   41,    32767, 521,   32767, 374,   -231,
		32767, 118,   248,   32767, 195,   -422,  32767, 567,
		483,   147,   32767, 864,   202,   32767, 502,   32767,
		0,     73,    32767, 0,     203,   32767, 32767, 32767,
		32767, 136,   0,     52,    32767, 32767, 32767, 313,
		-697,  32767, 0,     -413,  378,   32767, 58,    32767,
		-723,  32767, 238,   0,     695,   743,   262,   462,
		-84,   32767, 141,   32767, 251,   32767, 0,     72,
		545,   -131,  0,     32767, 105,   32767, 32767, -312,
		429,   0,     194,   0,     1108,  32767, 32767, 32767,
		0,     324,   32767, -163,  0,     229,   73,    32767,
		277,   32767, 437,   32767, 0,     0,     32767, 0,
		92,    32767, 68,    32767, 522,   136,   32767, 0,
		32767, 32767, 0,     -107,  -176,  0,     32767, 32767,
		312,   0,     400,   32767, 32767, 426,   355,   368,
		32767, 70,    32767, 101,   423,   32767, 173,   0,
		32767, 32767, -902,  44,    32767, 176,   5,     68,
		279,   379,   32767, 30,    -4,    0,     32767, 32767,
		32767, 32767, 359,   712,   326,   32767, 0,     32767,
		32767, 32767, 35,    0,     -856,  -539,  291,   0,
		162,   0,     411,   32767, 294,   245,   484,   109,
		32767, 367,   -15,   353,   32767, 167,   254,   79,
		32767, 32767, 0,     -290,  311,   32767, 101,   530,
		0,     32767, 32767, 32767, 32767, 0,     418,   32767,
		453,   102,   224,   32767, -152,  89,    445,   32767,
		32767, -427,  32767, 0,     32767, 32767, 52,    355,
		32767, 32767, 1203,  0,     32767, 540,   32767, -280,
		154,   32767, 32767, 32767, 301,   209,   32767, 432,
		32767, 32767, 171,   0,     7,     32767, 0,     32767,
		-157,  32767, 245,   32767, 252,   32767, 159,   625,
		32767, 32,    292,   32767, 32767, 0,     -21,   178,
		32767, 32767, 32767, 19,    -299,  0,     32767, 84,
		32767, 0,     32767, 32767, 1049,  32767, 333,   214,
		1110,  124,   -57,   -86,   0,     0,     0,     32767,
		272,   -194,  32767, 188,   32767, 32767, 111,   32767,
		0,     32767, 0,     197,   -415,  32767, -537,  32767,
		32767, 744,   32767, 133,   0,     32767, 32767, 210,
		-676,  54,    323,   -64,   417,   32767, 515,   0,
		0,     237,   168,   32767, 32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 1141] + h[b % 1141];
}

extern PGDLLIMPORT const ScanKeywordList OraScanKeywords;

const ScanKeywordList OraScanKeywords = {
	OraScanKeywords_kw_string,
	OraScanKeywords_kw_offsets,
	OraScanKeywords_hash_func,
	ORASCANKEYWORDS_NUM_KEYWORDS,
	22
};

#endif							/* ORA_KWLIST_D_H */
