/*-------------------------------------------------------------------------
 *
 * ora_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef ORA_KWLIST_D_H
#define ORA_KWLIST_D_H

#include "common/kwlookup.h"

static const char OraScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"accessible\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authid\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_float\0"
	"binary_float_infinity\0"
	"binary_float_nan\0"
	"bit\0"
	"body\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compile\0"
	"compression\0"
	"concurrently\0"
	"conditional\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"date\0"
	"day\0"
	"deallocate\0"
	"debug\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"editionable\0"
	"else\0"
	"empty\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enforced\0"
	"enum\0"
	"error\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"exec\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extend\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"ivysql\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_exists\0"
	"json_object\0"
	"json_objectagg\0"
	"json_query\0"
	"json_scalar\0"
	"json_serialize\0"
	"json_table\0"
	"json_value\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"loop\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"merge_action\0"
	"metadata\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"nested\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"nocache\0"
	"nocopy\0"
	"nocycle\0"
	"noextend\0"
	"nokeep\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"noneditionable\0"
	"noorder\0"
	"normalize\0"
	"normalized\0"
	"noscale\0"
	"noshard\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"nvl\0"
	"nvl2\0"
	"object\0"
	"objects\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"omit\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parallel\0"
	"parallel_enable\0"
	"parameter\0"
	"paramslength\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"path\0"
	"pgextract\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"polymorphic\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"quotes\0"
	"range\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"relies_on\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"result_cache\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rowid\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"scale\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"settings\0"
	"shard\0"
	"share\0"
	"sharing\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"specification\0"
	"sql\0"
	"sql_macro\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"string\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"systimestamp\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unconditional\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"updatexml\0"
	"user\0"
	"userenv\0"
	"using\0"
	"using_nls_comp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 OraScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	40,
	47,
	51,
	57,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	125,
	128,
	132,
	143,
	153,
	164,
	175,
	178,
	185,
	192,
	202,
	209,
	223,
	232,
	239,
	245,
	253,
	260,
	267,
	281,
	304,
	322,
	335,
	357,
	374,
	378,
	383,
	391,
	396,
	404,
	407,
	412,
	418,
	423,
	430,
	438,
	447,
	452,
	457,
	465,
	471,
	476,
	486,
	502,
	508,
	519,
	525,
	531,
	539,
	548,
	556,
	566,
	573,
	581,
	589,
	598,
	605,
	615,
	623,
	635,
	648,
	660,
	674,
	683,
	694,
	705,
	717,
	725,
	734,
	745,
	750,
	755,
	762,
	768,
	772,
	777,
	785,
	801,
	814,
	827,
	842,
	855,
	873,
	886,
	893,
	899,
	904,
	913,
	918,
	922,
	933,
	939,
	943,
	951,
	959,
	966,
	974,
	983,
	994,
	1003,
	1011,
	1018,
	1028,
	1039,
	1047,
	1053,
	1058,
	1065,
	1079,
	1090,
	1098,
	1106,
	1115,
	1118,
	1127,
	1134,
	1141,
	1146,
	1151,
	1163,
	1168,
	1174,
	1181,
	1190,
	1200,
	1204,
	1213,
	1218,
	1224,
	1231,
	1237,
	1244,
	1252,
	1262,
	1272,
	1277,
	1285,
	1292,
	1300,
	1311,
	1318,
	1328,
	1337,
	1345,
	1351,
	1358,
	1364,
	1371,
	1380,
	1386,
	1392,
	1402,
	1406,
	1412,
	1420,
	1427,
	1435,
	1442,
	1447,
	1452,
	1461,
	1471,
	1481,
	1488,
	1494,
	1502,
	1511,
	1517,
	1526,
	1533,
	1541,
	1546,
	1553,
	1560,
	1565,
	1570,
	1579,
	1582,
	1588,
	1598,
	1608,
	1617,
	1624,
	1627,
	1635,
	1645,
	1655,
	1662,
	1668,
	1676,
	1685,
	1693,
	1702,
	1712,
	1719,
	1725,
	1731,
	1737,
	1749,
	1756,
	1764,
	1768,
	1776,
	1786,
	1795,
	1800,
	1810,
	1818,
	1821,
	1828,
	1838,
	1845,
	1850,
	1855,
	1866,
	1880,
	1892,
	1904,
	1919,
	1930,
	1942,
	1957,
	1968,
	1979,
	1984,
	1988,
	1993,
	1999,
	2008,
	2014,
	2019,
	2027,
	2035,
	2045,
	2051,
	2056,
	2062,
	2067,
	2073,
	2080,
	2085,
	2091,
	2101,
	2116,
	2125,
	2130,
	2137,
	2144,
	2149,
	2154,
	2162,
	2168,
	2176,
	2189,
	2198,
	2204,
	2217,
	2226,
	2233,
	2240,
	2249,
	2254,
	2261,
	2267,
	2272,
	2277,
	2283,
	2287,
	2296,
	2304,
	2310,
	2317,
	2321,
	2326,
	2330,
	2334,
	2339,
	2344,
	2347,
	2355,
	2362,
	2370,
	2379,
	2386,
	2397,
	2408,
	2413,
	2428,
	2436,
	2446,
	2457,
	2465,
	2473,
	2477,
	2485,
	2492,
	2500,
	2507,
	2512,
	2519,
	2525,
	2532,
	2540,
	2544,
	2549,
	2556,
	2564,
	2567,
	2571,
	2578,
	2583,
	2587,
	2592,
	2595,
	2600,
	2609,
	2616,
	2624,
	2627,
	2633,
	2644,
	2651,
	2655,
	2661,
	2666,
	2675,
	2683,
	2694,
	2700,
	2706,
	2714,
	2723,
	2732,
	2748,
	2758,
	2771,
	2778,
	2786,
	2796,
	2804,
	2813,
	2818,
	2828,
	2838,
	2846,
	2851,
	2857,
	2864,
	2876,
	2885,
	2895,
	2905,
	2913,
	2922,
	2931,
	2939,
	2945,
	2956,
	2967,
	2977,
	2988,
	2996,
	3008,
	3014,
	3021,
	3027,
	3031,
	3036,
	3041,
	3050,
	3058,
	3068,
	3072,
	3083,
	3095,
	3103,
	3111,
	3120,
	3128,
	3138,
	3145,
	3156,
	3164,
	3172,
	3178,
	3186,
	3195,
	3208,
	3215,
	3225,
	3233,
	3239,
	3246,
	3252,
	3257,
	3266,
	3273,
	3281,
	3290,
	3294,
	3300,
	3307,
	3312,
	3320,
	3325,
	3335,
	3342,
	3348,
	3355,
	3363,
	3370,
	3377,
	3384,
	3393,
	3400,
	3409,
	3419,
	3432,
	3439,
	3447,
	3460,
	3464,
	3470,
	3475,
	3484,
	3490,
	3496,
	3504,
	3509,
	3517,
	3524,
	3529,
	3538,
	3547,
	3552,
	3559,
	3573,
	3577,
	3587,
	3594,
	3605,
	3611,
	3621,
	3632,
	3638,
	3645,
	3653,
	3660,
	3667,
	3674,
	3680,
	3693,
	3703,
	3711,
	3721,
	3729,
	3735,
	3742,
	3754,
	3767,
	3773,
	3780,
	3792,
	3803,
	3810,
	3815,
	3824,
	3834,
	3839,
	3844,
	3849,
	3854,
	3864,
	3867,
	3876,
	3888,
	3898,
	3904,
	3912,
	3917,
	3922,
	3931,
	3939,
	3944,
	3950,
	3958,
	3968,
	3980,
	3994,
	4006,
	4012,
	4019,
	4027,
	4036,
	4045,
	4051,
	4058,
	4068,
	4073,
	4081,
	4087,
	4102,
	4109,
	4115,
	4124,
	4134,
	4140,
	4147,
	4155,
	4164,
	4173,
	4181,
	4189,
	4197,
	4202,
	4208,
	4216,
	4224,
	4233,
	4238,
	4244,
	4255,
	4262,
	4267,
	4274,
	4282,
	4287,
	4295,
	4301,
	4305,
	4319,
	4329,
	4340,
	4350,
	4360,
	4374,
	4383,
	4389,
	4397,
	4410,
	4419,
	4424,
	4428,
};

#define ORASCANKEYWORDS_NUM_KEYWORDS 562

static int
OraScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1125] = {
		165,   0,     32767, 305,   -3,    25,    913,   32767,
		-513,  32767, 362,   0,     964,   312,   618,   -447,
		32767, 32767, 32767, 32767, 843,   528,   32767, 32767,
		32767, 32767, 209,   66,    32767, 32767, 32767, -341,
		337,   328,   32767, 553,   371,   390,   32767, 239,
		-85,   -182,  32767, -165,  0,     32767, 32767, 93,
		612,   32767, 32767, 0,     155,   225,   897,   469,
		32767, 800,   452,   0,     -784,  32767, 32767, -549,
		516,   -91,   730,   773,   32767, 487,   0,     0,
		287,   253,   -80,   32767, 32767, 32767, 227,   32767,
		0,     0,     32767, 119,   -359,  40,    32767, -26,
		386,   182,   79,    32767, 303,   32767, 0,     201,
		515,   32767, 222,   -613,  -313,  382,   32767, -68,
		32767, 367,   403,   32767, 32767, 32767, 0,     212,
		32767, 32767, 32767, 515,   499,   -25,   85,    -263,
		0,     32767, 542,   -228,  0,     -445,  1090,  32767,
		286,   32767, 32767, 32767, 187,   32767, 157,   32767,
		32767, 32767, 32767, -66,   32767, 32767, 32767, 32767,
		134,   390,   142,   32767, 496,   32767, -171,  32767,
		-70,   32767, 32767, 0,     -54,   32767, 32767, 32767,
		32767, 219,   0,     0,     32767, -127,  635,   159,
		-651,  32767, 558,   32767, 113,   0,     473,   -170,
		438,   32767, 32767, 32767, 32767, 0,     474,   795,
		569,   -522,  4,     0,     234,   118,   194,   -215,
		0,     90,    235,   0,     521,   0,     0,     66,
		32767, 61,    32767, 0,     -253,  -63,   49,    -337,
		244,   32767, 32767, -99,   104,   628,   -31,   32767,
		-160,  32767, 182,   365,   32767, 32767, 34,    0,
		32767, 32767, 32767, -706,  32767, -117,  32767, 101,
		32767, 0,     -499,  32767, 8,     32767, 32767, -305,
		63,    32767, 218,   137,   352,   480,   1393,  180,
		0,     490,   7,     -402,  -139,  32767, -190,  161,
		735,   -14,   19,    199,   738,   32,    357,   32767,
		0,     0,     644,   502,   293,   132,   389,   434,
		32767, 32767, 32767, 61,    0,     32767, 125,   -253,
		32767, 166,   20,    32767, 32767, 32767, 32767, 32767,
		32767, -222,  32767, 395,   -40,   32767, 19,    809,
		208,   32767, 32767, 32767, 268,   -530,  32767, 340,
		737,   32767, 492,   -265,  942,   32767, 216,   257,
		88,    4,     0,     32767, 32767, -383,  -280,  51,
		-186,  171,   32767, 32767, 32767, 107,   32767, -16,
		-176,  225,   533,   127,   32767, -39,   378,   32767,
		32767, 32767, 476,   -442,  32767, 258,   -28,   372,
		540,   32767, 59,    363,   32767, 16,    166,   0,
		32767, 124,   402,   499,   286,   32767, 335,   32767,
		32767, 32767, -93,   32767, -76,   -389,  28,    418,
		-593,  58,    59,    80,    32767, 32767, 411,   -225,
		32767, -477,  332,   32767, 659,   244,   0,     32767,
		455,   0,     370,   32767, 0,     32767, 32767, 216,
		0,     32767, 264,   32767, 266,   0,     32767, 276,
		0,     32767, 32767, -50,   32767, -456,  561,   -450,
		461,   32767, 462,   32767, 32767, 293,   526,   525,
		-608,  419,   0,     32767, -422,  32767, 32767, 32767,
		149,   32767, 0,     247,   32767, 548,   32767, 32767,
		5,     -193,  32767, 32767, 164,   0,     32767, 32767,
		32767, 630,   426,   -54,   32767, 400,   -235,  -140,
		32767, 32767, 32767, 39,    0,     315,   32767, 190,
		32767, 32767, 21,    725,   414,   280,   0,     0,
		13,    776,   0,     220,   112,   32767, 0,     32767,
		873,   0,     26,    232,   32767, 32767, 32767, -262,
		32767, 2,     324,   40,    32767, 240,   282,   32767,
		0,     32767, 32767, 55,    -27,   -201,  -419,  32767,
		-324,  -106,  0,     44,    865,   32767, 211,   32767,
		-411,  495,   -469,  0,     32767, 32767, 0,     0,
		349,   32767, -39,   32767, 336,   32767, 0,     185,
		264,   32767, 52,    361,   32767, 32767, 525,   32767,
		32767, 780,   32767, 32767, 32767, 263,   255,   0,
		32767, 0,     32767, -822,  -444,  99,    -374,  0,
		-218,  32767, 614,   351,   32767, 131,   32767, 342,
		32767, 636,   -577,  144,   32767, 48,    32767, -575,
		532,   32767, 187,   -961,  46,    32767, 32767, 32767,
		915,   -284,  32767, 32767, -363,  0,     -298,  32767,
		-30,   32767, 292,   -69,   -292,  -439,  547,   32767,
		32767, 269,   127,   542,   0,     51,    306,   493,
		32767, 0,     556,   32767, 0,     0,     66,    -232,
		32767, 32767, 32767, 250,   0,     0,     302,   70,
		32767, 0,     385,   32767, 143,   77,    32767, 0,
		0,     505,   0,     32767, 32767, 0,     55,    32767,
		0,     207,   -278,  0,     -677,  32767, 32767, 381,
		67,    0,     15,    32767, 32,    89,    0,     32767,
		206,   0,     -522,  -38,   32767, 32767, 32767, 32767,
		32767, 32767, 392,   -250,  545,   32767, 32767, -165,
		426,   32767, 415,   0,     571,   32767, 211,   32767,
		41,    32767, 32767, -293,  437,   455,   329,   150,
		32767, 309,   128,   32767, 32767, 0,     32767, 32767,
		32767, 32767, 32767, -109,  -500,  86,    32767, 485,
		32767, 116,   32767, -506,  344,   329,   -234,  265,
		32767, 0,     32767, 736,   466,   553,   32767, 320,
		184,   0,     32767, -18,   177,   32767, 240,   0,
		0,     32767, 32767, -352,  244,   32767, 32767, 32767,
		32767, 448,   -192,  429,   0,     0,     32767, 405,
		32767, 124,   269,   0,     281,   32767, 32767, 32767,
		32767, 72,    205,   32767, 447,   0,     -355,  0,
		362,   32767, 380,   32767, -4,    340,   108,   305,
		0,     0,     -77,   32767, 0,     32767, 32767, 32767,
		0,     32767, -29,   32767, 103,   32767, 32767, 588,
		331,   32767, 32767, 32767, 0,     412,   511,   57,
		32767, 32767, -104,  248,   74,    32767, 32767, 81,
		0,     -360,  273,   32767, 32767, 310,   212,   32767,
		142,   32767, 0,     32767, 54,    482,   538,   0,
		0,     88,    32767, -907,  188,   357,   0,     -47,
		0,     32767, 969,   32767, 169,   540,   98,    32767,
		-10,   32767, 32767, 32767, 32767, -120,  -253,  0,
		-5,    -81,   32767, 203,   32767, 32767, 0,     32767,
		32767, 0,     259,   369,   233,   32767, 32767, 37,
		0,     275,   0,     549,   0,     32767, 32767, 32767,
		32767, 721,   366,   32767, 358,   0,     0,     324,
		271,   32767, 0,     32767, 32767, -94,   32767, 32767,
		0,     -8,    32767, -239,  0,     -220,  90,    506,
		0,     32767, 32767, 109,   408,   32767, 32767, 818,
		82,    0,     387,   39,    0,     32767, 0,     32767,
		32767, 32767, 395,   0,     87,    32767, 0,     675,
		32767, 500,   57,    32767, 777,   32767, 126,   -291,
		32767, 32767, 124,   32767, 32767, 32767, 0,     0,
		32767, 0,     32767, 50,    0,     7,     391,   32767,
		338,   32767, 373,   32767, -61,   872,   32767, 0,
		555,   32767, 191,   949,   100,   32767, -76,   32767,
		85,    -152,  422,   32767, 32767, 32767, 32767, 136,
		173,   32767, 0,     399,   32767, 128,   38,    421,
		223,   32767, -74,   0,     0,     32767, 314,   0,
		32767, 32767, 0,     -505,  32767, 871,   973,   146,
		32767, 129,   573,   32767, 283,   0,     32767, 172,
		0,     0,     32767, 32767, 435,   32767, -202,  -7,
		32767, 638,   248,   483,   247,   32767, 774,   270,
		228,   -4,    0,     68,    32767, 32767, 0,     202,
		-317,  32767, 0,     -69,   32767, 0,     95,    32767,
		144,   0,     0,     0,     32767, -507,  285,   32767,
		32767, -28,   32767, 0,     32767, 469,   32767, 32767,
		436,   333,   32767, 32767, 0,     32767, 121,   1023,
		32767, 556,   88,    409,   75,    0,     32767, 32767,
		488,   0,     0,     32767, 498,   -62,   32767, 323,
		32767, 0,     0,     0,     225,   32767, 32767, 213,
		130,   32767, -47,   32767, 32767, -33,   221,   125,
		32767, 32767, 163,   422,   32767, 375,   0,     -173,
		32,    32767, 32767, 539,   294,   295,   0,     32767,
		123,   388,   275,   610,   32767, 14,    460,   365,
		32767, 32767, 0,     386,   32767, 147,   32767, 0,
		366,   32767, 32767, 339,   32767, 32767, 0,     -2,
		32767, 32767, 266,   32767, 32767, 0,     82,    0,
		32767, 0,     32767, 32767, 32767, 32767, 0,     -115,
		32767, 32767, 363,   0,     0
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1125] + h[b % 1125];
}

const ScanKeywordList OraScanKeywords = {
	OraScanKeywords_kw_string,
	OraScanKeywords_kw_offsets,
	OraScanKeywords_hash_func,
	ORASCANKEYWORDS_NUM_KEYWORDS,
	22
};

#endif							/* ORA_KWLIST_D_H */
