#-------------------------------------------------------------------------
# Copyright 2025 IvorySQL Global Development Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for src/pl/plisql (IvorySQL's PLISQL procedural language)
#
# Portions Copyright (c) 2023-2026, IvorySQL Global Development Team
#
# src/pl/plisql/Makefile
#
# add the file for requirement "SQL PARSER"
#
#-------------------------------------------------------------------------

subdir = src/pl/plisql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
