#-------------------------------------------------------------------------
#
# Makefile for src/pl/plisql (IvorySQL's PLISQL procedural language)
#
# Portions Copyright (c) 2023-2025, IvorySQL Global Development Team
#
# src/pl/plisql/Makefile
#
# add the file for requirement "SQL PARSER"
#
#-------------------------------------------------------------------------

subdir = src/pl/plisql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
