set datestyle to ISO,YMD;
set search_path to oracle, pg_catalog;
SELECT ltrim(121232112, 21) "LTRIM Example";
SELECT ltrim(121232112) "LTRIM Example";
SELECT ltrim(12312::int2, 21::int2) "LTRIM Example";
SELECT ltrim(1223112::int4, 21::int4) "LTRIM Example";
SELECT ltrim(1223112::int4) "LTRIM Example";
SELECT ltrim(121232112::int8, 21::int8) "LTRIM Example";
SELECT ltrim(2.13232112, 2.1) "LTRIM Example";
SELECT ltrim(2.13232112::numeric, 2.1::numeric) "LTRIM Example";
SELECT ltrim(2.13232112::numeric) "LTRIM Example";
SELECT ltrim('1213232112', '21') "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>', '<>=') "LTRIM Example";
SELECT ltrim('   ab cdea  ') "LTRIM Example";
SELECT ltrim('   ab cdea  '::char(4)) "LTRIM Example";
SELECT ltrim('   ab cdea  '::char(20)) "LTRIM Example";
SELECT length(ltrim('   ab cdea  '::char(20))) "LTRIM Example";
SELECT ltrim('   ab cdea  '::varchar2(20)) "LTRIM Example";
SELECT ltrim('   ab cdea  '::text) "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>'::char(25), '<>='::char(3)) "LTRIM Example";
SELECT length(ltrim('<=====>BROWNING<=====>'::char(25), '<>='::char(3))) "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>'::varchar(25), '<>='::varchar(5)) "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>'::varchar2(25), '<>='::varchar2(5)) "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>'::nvarchar2(25), '<>='::nvarchar2(5)) "LTRIM Example";
SELECT ltrim('<=====>BROWNING<=====>'::text, '<>='::text) "LTRIM Example";
SELECT ltrim('我的家我的梦'::varchar2(25), '我的家'::varchar2(9)) "LTRIM Example";
SELECT ltrim('2019-12-12'::date, '2019-12-12'::date) "LTRIM Example";
SELECT ltrim('2019-12-12'::timestamp, '2019-12-12'::timestamp) "LTRIM Example";
SELECT ltrim('2019-12-12'::date) "LTRIM Example";
SELECT ltrim(null,'nu'::text);
SELECT ltrim('nu'::text,null);
SELECT ltrim(null,null);
SELECT ltrim('','');
SELECT ltrim('',' ');
SELECT ltrim(' ','');
SELECT ltrim(' ',' ');
SELECT ltrim(null);
SELECT ltrim('');
SELECT ltrim(' ');
SELECT ltrim(0::int,0.99::numeric);
SELECT ltrim(-1::int,-1::int);
SELECT ltrim(0::int);
SELECT ltrim(-5::int);
SELECT ltrim(0.99::numeric);
SELECT ltrim(-5.99::numeric);

reset search_path;
