/*-------------------------------------------------------------------------
 *
 * pg_force_view_d.h
 *    Macro definitions for pg_force_view
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_FORCE_VIEW_D_H
#define PG_FORCE_VIEW_D_H

/* Macros related to the structure of pg_force_view */

#define ForceViewRelationId 9120
#define ForceViewFvoidIndexId 9123

#define Anum_pg_force_view_fvoid 1
#define Anum_pg_force_view_ident_case 2
#define Anum_pg_force_view_source 3

#define Natts_pg_force_view 3

/* Definitions copied from pg_force_view.h */


/* OID symbols for objects defined in pg_force_view.dat */


#endif							/* PG_FORCE_VIEW_D_H */
