/*-------------------------------------------------------------------------
 *
 * pg_package_d.h
 *    Macro definitions for pg_package
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PACKAGE_D_H
#define PG_PACKAGE_D_H

/* Macros related to the structure of pg_package */

#define PackageRelationId 9111
#define PackageObjectIndexId 9114
#define PackageNameArgsNspIndexId 9115

#define Anum_pg_package_oid 1
#define Anum_pg_package_pkgname 2
#define Anum_pg_package_pkgnamespace 3
#define Anum_pg_package_pkgowner 4
#define Anum_pg_package_define_invok 5
#define Anum_pg_package_editable 6
#define Anum_pg_package_use_collation 7
#define Anum_pg_package_pkgacl 8
#define Anum_pg_package_accesssource 9
#define Anum_pg_package_pkgsrc 10

#define Natts_pg_package 10

/* Definitions copied from pg_package.h */


/* OID symbols for objects defined in pg_package.dat */


#endif							/* PG_PACKAGE_D_H */
