/*-------------------------------------------------------------------------
 *
 * pg_package_body_d.h
 *    Macro definitions for pg_package_body
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PACKAGE_BODY_D_H
#define PG_PACKAGE_BODY_D_H

/* Macros related to the structure of pg_package_body */

#define PackageBodyRelationId 9106
#define PackageBodyObjectIndexId 9109
#define PackageBodyPkgOidIndex 9110

#define Anum_pg_package_body_oid 1
#define Anum_pg_package_body_pkgoid 2
#define Anum_pg_package_body_bodysrc 3

#define Natts_pg_package_body 3

/* Definitions copied from pg_package_body.h */


/* OID symbols for objects defined in pg_package_body.dat */


#endif							/* PG_PACKAGE_BODY_D_H */
