name: contrib_regression

on:
  push:
    branches: [ master , IVORY_REL_3_STABLE ]
  pull_request:
    branches: [ master , IVORY_REL_3_STABLE ]

jobs:
  contrib_regression:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependancy
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git lcov bison flex \
              libkrb5-dev libssl-dev libldap-dev libpam-dev python3-dev \
              tcl-dev libperl-dev gettext libxml2-dev libxslt-dev \
              libreadline-dev libedit-dev uuid-dev libossp-uuid-dev \
              libipc-run-perl libtime-hires-perl libtest-simple-perl \
              libicu-dev
    - name: configure - linux
      run: |
        curl -L -o cpanm http://cpanmin.us && chmod +x cpanm && \
        ./cpanm --sudo IPC::Run && \
        ./configure \
            --prefix=$PWD/inst \
            --enable-cassert --enable-debug --enable-tap-tests --enable-rpath \
            --with-tcl --with-python --with-gssapi --with-pam --with-ldap \
            --with-openssl --with-libedit-preferred --with-uuid=e2fs \
            --with-ossp-uuid  --with-libxml --with-libxslt  --with-perl \
            --with-icu
    - name: compile
      run: make && make install

    - name: contrib_regression
      run: |
        cd contrib && make oracle-check
        make check

    - name: collect files
      if: failure()
      run: |
          find . \( -name "*.diffs" -or -name "pg_regression.out" -or -path \*/tmp_check/log -or -path \*src/test/regress/log \) -print0 |
                xargs -0 tar -czf pg_regression.tar.gz
    - name: upload pg_regression files
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ${{ github.workspace }}/pg_regression.tar.gz

