name: meson_build

on:
  push:
    branches: [ master , IVORY_REL_3_STABLE ]
  pull_request:
    branches: [ master , IVORY_REL_3_STABLE ]

jobs:
  meson_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    steps:
    - uses: actions/checkout@v3
    - name: dependancy - linux
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git lcov bison flex \
              libkrb5-dev libssl-dev libldap-dev libpam-dev python3-dev \
              tcl-dev libperl-dev gettext libxml2-dev libxslt-dev \
              libreadline-dev libedit-dev uuid-dev libossp-uuid-dev \
              libipc-run-perl libtime-hires-perl libtest-simple-perl \
              libgssapi-krb5-2 libicu-dev
        curl -L "https://github.com/mesonbuild/meson/releases/download/0.57.2/meson-0.57.2.tar.gz" -o meson-0.57.2.tar.gz
        curl -L "https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-linux.zip" -o ninja-linux.zip
        unzip -o ninja-linux.zip
        sudo cp ninja /usr/bin/
        tar xzf meson-0.57.2.tar.gz
        cd meson-0.57.2
        sudo python3 setup.py install
    
    - name: configure - linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        meson setup build \
            -Dcassert=true \
            -Dbuildtype=debug

    - name: compile
      run: |
        cd build && ninja -j1
